-- MySQL Script generated by MySQL Workbench
-- Wed Nov  1 16:29:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurant` DEFAULT CHARACTER SET utf8mb4 ;
USE `Restaurant` ;

-- -----------------------------------------------------
-- Table `Restaurant`.`JobTitle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`JobTitle` (
  `jobTitle_id` INT NOT NULL AUTO_INCREMENT,
  `jobTitle` VARCHAR(45) NULL,
  PRIMARY KEY (`jobTitle_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `orders` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jobTitle_idx` (`orders` ASC) VISIBLE,
  CONSTRAINT `fk_jobTitle`
    FOREIGN KEY (`orders`)
    REFERENCES `Restaurant`.`JobTitle` (`jobTitle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` INT NULL,
  `statusCook` VARCHAR(45) NULL,
  `statusWaiter` VARCHAR(45) NULL,
  `orderList` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Restaurant`.`JobTitle`
-- -----------------------------------------------------
START TRANSACTION;
USE `Restaurant`;
INSERT INTO `Restaurant`.`JobTitle` (`jobTitle_id`, `jobTitle`) VALUES (1, 'Администратор');
INSERT INTO `Restaurant`.`JobTitle` (`jobTitle_id`, `jobTitle`) VALUES (2, 'Повар');
INSERT INTO `Restaurant`.`JobTitle` (`jobTitle_id`, `jobTitle`) VALUES (3, 'Оффициант');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Restaurant`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `Restaurant`;
INSERT INTO `Restaurant`.`Users` (`id`, `login`, `password`, `orders`) VALUES (1, 'kuzya1009', '25092004', 2);
INSERT INTO `Restaurant`.`Users` (`id`, `login`, `password`, `orders`) VALUES (2, 'Dish4', 'kZw1HVEWa', 1);

COMMIT;

